name: GitHub Basic Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests
      - name: Setup Go 1.21.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          # TODO insert your variant
          collection: postman/[avito]Banner_system.postman_collection
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v